version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - dot_amplify:/root/.amplify
      - dot_aws:/root/.aws

    tty: true
volumes:
  bundle:
  dot_amplify:
  dot_aws:
