version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
volumes:
  bundle:
    driver: local
